#!/usr/bin/python
# poweroff the virtual machine in  

import os
import re
import sys

# note the print will append extra newline character at the
# end of the string, to print it explicity use print(repr(str))
vm_run = frozenset(os.popen("VBoxManage list runningvms"))


vm_size = len(vm_run)
if vm_size == 0:
    print("No virtual machines are running.")
    exit(0)

vm_list = []
index = 1
for vm in vm_run:
    vm = re.findall(r'"([^"]*)"', vm)[0]
    print("[{0}] {1}".format(index, vm))
    vm_list.append(vm)
    index = index + 1

prompt = "Enter the virtual machine to power off"
if vm_size == 1:
    prompt = prompt + "[1]: "
else:
    prompt = prompt + "[1-{0}]: ".format(vm_size)
target = input(prompt) - 1
while target < 0 or target >= vm_size:
    print("Enter invalid number.")
    target = input(prompt) - 1
init_cmd = "VBoxManage controlvm " + "\"" + vm_list[target]  + "\"" + " acpipowerbutton"
os.popen(init_cmd)

exit()