#!/bin/bash

function _inst_llvm()
{
    #
    # Add the archive signature
    #
    // wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    #
    # Add the PPA
    #
    // sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main"
    sudo apt-get update
    #
    # Allow the Repository to reload and then run the following command
    #
    // sudo apt-get install clang-3.9 lldb-3.9
    sudo apt-get install clang
    #
    # Test your installation as follows, as shown on my own Xenial system
    #
    clang --version
}

function _inst_qemu(parameter)
{
    sudo apt-get install qemu
    #
    # for xv6
    #
    sudo apt-get install libc6-dev:i386
}

function _DragLock_And_PalmDetect()
{
    #
    # This enable the DragLock and PalmDetection function
    #
    local XorgConf="/usr/share/X11/xorg.conf.d/60-synaptics-options.conf"
    echo 'Section "InputClass"'                                                  >${XorgConf}
    echo '    Identifier "touchpad catchall"'                                   >>${XorgConf}
    echo '    Driver "synaptics"'                                               >>${XorgConf}
    echo '    MatchIsTouchpad "on"'                                             >>${XorgConf}
#    echo 'MatchDevicePath "/dev/input/event*"' >>${XorgConf}
    echo '    Option "LockedDrags" "1"'                                         >>${XorgConf}
    echo '    Option "PalmDetect" "1"'                                          >>${XorgConf}
    echo 'EndSection'                                                           >>${XorgConf}
}

function _disSuspend()
{
    #
    # Note: we'd better disable hibernate/suspend mode on x205ta because
    # it will very likely panic the system. Sleep perform pretty well
    # if you close the lid. We also need to disable the Suspend button
    # in menu as well
    #
    local dSuspendConf="/etc/polkit-1/localauthority/50-local.d/com.ubuntu.disable-suspend.pkla"
    echo '[Disable suspend (upower)]'                                            >${dSuspendConf}
    echo 'Identity=unix-user:*'                                                 >>${dSuspendConf}
    echo 'Action=org.freedesktop.upower.suspend'                                >>${dSuspendConf}
    echo 'ResultActive=no'                                                      >>${dSuspendConf}
    echo 'ResultInactive=no'                                                    >>${dSuspendConf}
    echo 'ResultAny=no'                                                         >>${dSuspendConf}
    echo ''                                                                     >>${dSuspendConf}
    echo '[Disable suspend (logind)]'                                           >>${dSuspendConf}
    echo 'Identity=unix-user:*'                                                 >>${dSuspendConf}
    echo 'Action=org.freedesktop.login1.suspend'                                >>${dSuspendConf}
    echo 'ResultActive=no'                                                      >>${dSuspendConf}
    echo 'ResultInactive=no'                                                    >>${dSuspendConf}
    echo 'ResultAny=no'                                                         >>${dSuspendConf}
    echo ''                                                                     >>${dSuspendConf}
    echo '[Disable suspend when others are logged in (logind)]'                 >>${dSuspendConf}
    echo 'Identity=unix-user:*'                                                 >>${dSuspendConf}
    echo 'Action=org.freedesktop.login1.suspend-multiple-sessions'              >>${dSuspendConf}
    echo 'ResultActive=no'                                                      >>${dSuspendConf}
    echo 'ResultInactive=no'                                                    >>${dSuspendConf}
    printf 'ResultAny=no'                                                       >>${dSuspendConf}
}

function main()
{
    _inst_llvm
    _inst_qemu
    _DragLock_And_PalmDetect
    _disSuspend

    exit 0
}

main
