#!/bin/bash

function _inst_llvm()
{
    #
    # Add the archive signature
    #
    // wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    #
    # Add the PPA
    #
    // sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main"
    sudo apt-get update
    #
    # Allow the Repository to reload and then run the following command
    #
    // sudo apt-get install clang-3.9 lldb-3.9
    sudo apt-get install clang
    #
    # Test your installation as follows, as shown on my own Xenial system
    #
    clang --version
}

function _inst_qemu(parameter)
{
    sudo apt-get install qemu
    #
    # for xv6
    #
    sudo apt-get install libc6-dev:i386
}

function _DragLock_And_PalmDetect()
{
	#
	# We need to disable system preference settings at first
	#
	dconf write /org/gnome/settings-daemon/plugins/mouse/active false
	#
	# I will refine this method(don't know why Ubuntu will overwrite some settings)
	#

    #
    # This enable the DragLock and PalmDetection function
    #
    local XorgConf="/usr/share/X11/xorg.conf.d/60-synaptics-options.conf"
    echo 'Section "InputClass"'                                                  >${XorgConf}
    echo '    Identifier "touchpad catchall"'                                   >>${XorgConf}
    echo '    Driver "synaptics"'                                               >>${XorgConf}
    echo '    MatchIsTouchpad "on"'                                             >>${XorgConf}
#    echo 'MatchDevicePath "/dev/input/event*"' >>${XorgConf}
    echo '    Option "LockedDrags" "1"'                                         >>${XorgConf}
    echo '    Option "PalmDetect" "1"'                                          >>${XorgConf}
    #
    # Enable 3 finger tap function (c) syscl
    #
    # you can test value by type in 
    # synclient "TapButton3"=XX
    # Note: XX has the following setting:
    # 1 - left button/click
    # 2 - middle button/click - same as keyboard 'Enter'
    # 3 - right button/click
    # 4 - scroll up a bit
    # 5 - scroll down a bit
    # 8 - previous page
    # 9 - next a page
    #
    echo '    Option "TapButton3" "8"'                                          >>${XorgConf}
    echo '    Option "VertScrollDelta" "-71"'				    				>>${XorgConf}
    #
    # '-'(minus sign) is for scrolling in reverse direction(natural scrolling)
    #
    echo '  Option "HorizScrollDelta" "-71"'									>>${XorgConf}
    echo '  Option "VertEdgeScroll" "0"'										>>${XorgConf}
    echo '  Option "HorizTwoFingerScroll" "1"'									>>${XorgConf}
    echo '  Option "TouchpadOff" "0"'											>>${XorgConf}
    echo 'EndSection'                                                           >>${XorgConf}
}

function _disSuspend()
{
    #
    # Note: we'd better disable hibernate/suspend mode on x205ta because
    # it will very likely panic the system. Sleep perform pretty well
    # if you close the lid. We also need to disable the Suspend button
    # in menu as well
    #
    local dSuspendConf="/etc/polkit-1/localauthority/50-local.d/com.ubuntu.disable-suspend.pkla"
    echo '[Disable suspend (upower)]'                                            >${dSuspendConf}
    echo 'Identity=unix-user:*'                                                 >>${dSuspendConf}
    echo 'Action=org.freedesktop.upower.suspend'                                >>${dSuspendConf}
    echo 'ResultActive=no'                                                      >>${dSuspendConf}
    echo 'ResultInactive=no'                                                    >>${dSuspendConf}
    echo 'ResultAny=no'                                                         >>${dSuspendConf}
    echo ''                                                                     >>${dSuspendConf}
    echo '[Disable suspend (logind)]'                                           >>${dSuspendConf}
    echo 'Identity=unix-user:*'                                                 >>${dSuspendConf}
    echo 'Action=org.freedesktop.login1.suspend'                                >>${dSuspendConf}
    echo 'ResultActive=no'                                                      >>${dSuspendConf}
    echo 'ResultInactive=no'                                                    >>${dSuspendConf}
    echo 'ResultAny=no'                                                         >>${dSuspendConf}
    echo ''                                                                     >>${dSuspendConf}
    echo '[Disable suspend when others are logged in (logind)]'                 >>${dSuspendConf}
    echo 'Identity=unix-user:*'                                                 >>${dSuspendConf}
    echo 'Action=org.freedesktop.login1.suspend-multiple-sessions'              >>${dSuspendConf}
    echo 'ResultActive=no'                                                      >>${dSuspendConf}
    echo 'ResultInactive=no'                                                    >>${dSuspendConf}
    printf 'ResultAny=no'                                                       >>${dSuspendConf}
}

function _inst_opencmd()
{
    sudo cp bin/open /usr/local/bin
}

function main()
{
    _inst_llvm
    _inst_qemu
    _DragLock_And_PalmDetect
    #_disSuspend
    _inst_opencmd

    exit 0
}

main
