#!/bin/bash

#
# Update/refresh system buffer/cache
#
# refresh font cache
sudo fc-cache -f -v
#
# update applications list
#
sudo apt-get update
#
# update boot config
#
sudo update-grub
#
# remove useless depedencies
#
sudo apt-get clean
sudo apt-get autoremove
